more die-fast error handling

diff --git a/docker/hooks/build b/docker/hooks/build
--- a/docker/hooks/build
+++ b/docker/hooks/build
@@ -70,8 +70,8 @@ main() {
 
         drawio | drawio-* | blender | blender-* | gimp | gimp-* | inkscape | inkscape-* | freecad | freecad-* )
 
+            ### no quotes around ${params}!
             set -x
-            ### no quotes around 'params'
             docker build ${params} \
                 -f "${DOCKERFILE_PATH}" \
                     --build-arg BASEIMAGE="${BASEIMAGE}" \
@@ -122,7 +122,11 @@ main() {
                     ${FEATURES_INKSCAPE:+--build-arg ARG_MERGE_STAGE_DRAWING_BASE="stage_inkscape"} \
                     \
                 -t "${DOCKER_REPO}:${DOCKER_TAG}${target_stage:+_${target_stage}}" "${_build_context}"
+            
+            exit_code=$?
             set +x
+            
+            if [[ ${exit_code} -ne 0 ]] ; then die "Failed to build image '${DOCKER_REPO}:${DOCKER_TAG}'" ${exit_code} ; fi
             ;;
 
         ### -----------------------------------------------
@@ -131,8 +135,8 @@ main() {
 
         latest | latest-* | vnc | vnc-* )
 
+            ### no quotes around ${params}!
             set -x
-            ### no quotes around 'params'
             docker build ${params} \
                 -f "${DOCKERFILE_PATH}" \
                     --build-arg BASEIMAGE="${BASEIMAGE}" \
@@ -169,7 +173,11 @@ main() {
                     ${FEATURES_FIREFOX_PLUS:+--build-arg ARG_MERGE_STAGE_BROWSER_BASE="stage_firefox_plus"} \
                     \
                 -t "${DOCKER_REPO}:${DOCKER_TAG}${target_stage:+_${target_stage}}" "${_build_context}"
+            
+            exit_code=$?
             set +x
+            
+            if [[ ${exit_code} -ne 0 ]] ; then die "Failed to build image '${DOCKER_REPO}:${DOCKER_TAG}'" ${exit_code} ; fi
             ;;
 
         * )
diff --git a/docker/hooks/pre_build b/docker/hooks/pre_build
--- a/docker/hooks/pre_build
+++ b/docker/hooks/pre_build
@@ -66,8 +66,8 @@ main() {
 
         drawio | drawio-* | blender | blender-* | gimp | gimp-* | inkscape | inkscape-* | freecad | freecad-* )
 
+            ### no quotes around ${params}!
             set -x
-            ### no quotes around 'params'
             docker build ${params} \
                 -f "${DOCKERFILE_PATH}" \
                     --build-arg BASEIMAGE="${BASEIMAGE}" \
@@ -114,7 +114,11 @@ main() {
                     ${FEATURES_INKSCAPE:+--build-arg ARG_MERGE_STAGE_DRAWING_BASE="stage_inkscape"} \
                     \
                 -t "${DOCKER_REPO}":"${DOCKER_TAG}${helper_suffix}" "${_build_context}"
+            
+            exit_code=$?
             set +x
+
+            if [[ ${exit_code} -ne 0 ]] ; then set +x; die "Failed to build image '${DOCKER_REPO}:${DOCKER_TAG}${helper_suffix}'" ${exit_code} ; fi
             ;;
 
         ### -----------------------------------------------
@@ -123,8 +127,8 @@ main() {
 
         latest | latest-* | vnc | vnc-* )
 
+            ### no quotes around ${params}!
             set -x
-            ### no quotes around 'params'
             docker build ${params} \
                 -f "${DOCKERFILE_PATH}" \
                     --build-arg BASEIMAGE="${BASEIMAGE}" \
@@ -157,7 +161,11 @@ main() {
                     ${FEATURES_FIREFOX_PLUS:+--build-arg ARG_MERGE_STAGE_BROWSER_BASE="stage_firefox_plus"} \
                     \
                 -t "${DOCKER_REPO}":"${DOCKER_TAG}${helper_suffix}" "${_build_context}"
+            
+            exit_code=$?
             set +x
+
+            if [[ ${exit_code} -ne 0 ]] ; then set +x; die "Failed to build image '${DOCKER_REPO}:${DOCKER_TAG}${helper_suffix}'" ${exit_code} ; fi
             ;;
 
         * )
diff --git a/docker/hooks/push b/docker/hooks/push
--- a/docker/hooks/push
+++ b/docker/hooks/push
@@ -13,6 +13,7 @@ deployment_push() {
     local target
     local repo="${_deploy_repo##*/}"
     local keeper_repo_tag="${_deploy_builder_tags[0]}"
+    local -i exit_code=0
 
     if [[ -n "${repo}" && "${repo}" != "${_prohibited_repo_name}" ]] ; then
 
@@ -26,9 +27,16 @@ deployment_push() {
                 target="${_deploy_repo}:${t}"
 
                 echo ; echo "Deploying image '${target}'"
+
                 docker tag "${DOCKER_REPO}:${keeper_repo_tag}" "${target}"
                 docker push "${target}"
+                exit_code=$?
                 docker rmi "${target}"
+
+                if [[ ${exit_code} -ne 0 ]] ; then
+                    docker logout
+                    die "Unable to push image '${target}'" ${exit_code}
+                fi
             fi
         done
 
@@ -41,6 +49,7 @@ main() {
     local target
     local repo="${DOCKER_REPO##*/}"
     local keeper_repo_tag="${_deploy_builder_tags[0]}"
+    local -i exit_code=0
 
     if [[ -f "${_build_context}/${_scrap_demand_stop_building}" ]] ; then
         echo "Skipping push on demand."
@@ -79,13 +88,24 @@ main() {
 
                     # first element is the master repo (a keeper)
                     docker push "${DOCKER_REPO}:${t}"
+                    exit_code=$?
 
+                    if [[ ${exit_code} -ne 0 ]] ; then
+                        docker logout
+                        die "Unable to push image '${DOCKER_REPO}:${t}'" ${exit_code}
+                    fi
                 else
                     target="${DOCKER_REPO}:${t}"
 
                     docker tag "${DOCKER_REPO}:${keeper_repo_tag}" "${target}"
                     docker push "${target}"
+                    exit_code=$?
                     docker rmi "${target}"
+
+                    if [[ ${exit_code} -ne 0 ]] ; then
+                        docker logout
+                        die "Unable to push image '${target}'" ${exit_code}
+                    fi
                 fi
             done
 
