Release 25.04

diff --git a/docker/hooks/cache b/docker/hooks/cache
--- a/docker/hooks/cache
+++ b/docker/hooks/cache
@@ -1,12 +1,37 @@
 #!/bin/bash
 
-### @accetto, September 2022
-
 echo -e "\n==> EXECUTING @$(date -u +'%Y-%m-%d_%H-%M-%S'): ${0} $@\n"
 
 declare _mydir=$(dirname $0)
 
 source "${_mydir}"/env.rc
+source "${_mydir}"/util.rc
+
+ensure_wget() {
+    local -i error_code=0
+    local -i enforced_error_code=1
+
+    ### checking can be disabled by passing 'enforced_error_code=0'
+    if [[ "${IGNORE_MISSING_WGET:-0}" == "0" ]] ; then
+        enforced_error_code=1
+    else
+        enforced_error_code=0
+    fi
+    ensure_utility wget ${enforced_error_code}
+
+    error_code=$?
+    if [[ ${error_code} -ne 0 ]] ; then
+        echo
+        echo "WARNING! Utility 'wget' not found."
+        echo "It's recommended to install the utility or to switch to an environment where it's available (e.g. WSL)."
+        echo "Otherwise set the environment variable IGNORE_MISSING_WGET=1 to ignore this checking."
+        echo "The selected packages still will be downloaded into a temporary image layer, but not into the project's"
+        echo "'.g3-cache' folder nor the shared one, defined by the variable SHARED_G3_CACHE_PATH."
+        echo
+
+        die "Utility 'wget' not found." ${error_code}
+    fi
+}
 
 use_wget() {
     local section="${1?Expected section name}"
@@ -27,7 +52,7 @@ use_wget() {
         wget --show-progress --progress=bar:force:noscroll ${_quiet:+-q} -O "${target}" "${source}"
 
     ) ; {
-        
+
         ### catch - this block is entered only by errors in the try-block
         error_code=$?
 
@@ -74,7 +99,7 @@ refresh_file() {
                 echo -e "${_mark} refreshing shared section '${section}' by copying downloaded file '${file}'\n"
 
                 mkdir -p "${_shared_cache_path}/${section}"
-                
+
                 cp "${target}" "${source}"
             fi
         fi
@@ -219,43 +244,46 @@ cache_freecad() {
 
 main() {
 
+    ensure_wget
+
+
     if [[ "${FEATURES_VNC}" == "1" ]] ; then
 
         cache_tigervnc
-        if [[ $? -ne 0 ]] ; then return 1; fi
+        if [[ $? -ne 0 ]] ; then return 1 ; fi
     fi
 
     if [[ "${FEATURES_NOVNC}" == "1" ]] ; then
 
         cache_novnc
-        if [[ $? -ne 0 ]] ; then return 1; fi
+        if [[ $? -ne 0 ]] ; then return 1 ; fi
 
         cache_websockify
-        if [[ $? -ne 0 ]] ; then return 1; fi
+        if [[ $? -ne 0 ]] ; then return 1 ; fi
     fi
 
     if [[ "${FEATURES_CHROMIUM}" == "1" ]] ; then
-    
+
         cache_chromium
-        if [[ $? -ne 0 ]] ; then return 1; fi
+        if [[ $? -ne 0 ]] ; then return 1 ; fi
     fi
 
     if [[ "${FEATURES_VIRTUALGL}" == "1" ]] ; then
-    
+
         cache_virtualgl
-        if [[ $? -ne 0 ]] ; then return 1; fi
+        if [[ $? -ne 0 ]] ; then return 1 ; fi
     fi
 
     if [[ "${FEATURES_DRAWIO}" == "1" ]] ; then
-    
+
         cache_drawio
-        if [[ $? -ne 0 ]] ; then return 1; fi
+        if [[ $? -ne 0 ]] ; then return 1 ; fi
     fi
 
     if [[ "${FEATURES_FREECAD}" == "1" ]] ; then
-    
+
         cache_freecad
-        if [[ $? -ne 0 ]] ; then return 1; fi
+        if [[ $? -ne 0 ]] ; then return 1 ; fi
     fi
 
     echo
@@ -266,7 +294,7 @@ declare _mark="\n==> G3-CACHE"
 declare _cache="${_build_context}/.g3-cache"
 declare _shared_cache_path="${SHARED_G3_CACHE_PATH}"
 
-if [[ $# -gt 0 && "${1}" =~ -q|--quiet ]] ; then 
+if [[ $# -gt 0 && "${1}" =~ -q|--quiet ]] ; then
 
     _quiet="q"
     shift
